### ISSUE TITLE
Add Ability to Add a Comment to a Question/Answer

### ISSUE THREAD

**Issue by tylerbwong** [tylerbwong/stack#109]
https://api.stackexchange.com/docs/create-comment

**Comment by KaKi87** [comment]
Hello,
Any news on this ?
Thanks

**Comment by tylerbwong** [comment]
Added in [2.0.0](https://github.com/tylerbwong/stack/releases/tag/2.0.0)

**Comment by KaKi87** [comment]
Please indicate that SO's 15 character requirement is the reason why the button is greyed out.

**Comment by tylerbwong** [comment]
Thanks @KaKi87, I opened #135 to track this.
