### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by 532910** [tylerbwong/stack#110]
Add it to F-Droid, please.

https://gitlab.com/fdroid/rfp/-/issues/1558

**Comment by licaon-kter** [comment]
All those non open-source dependencies need to be separated in a flavor or something, first.

**Comment by tylerbwong** [comment]
Hi @532910, thanks for the issue and the submission on GitLab. I had originally thought of uploading an APK to F-Droid before I ended up putting it on the Play Store, however I have not considered it since.

Let me do a bit more research before proceeding with https://gitlab.com/fdroid/rfp/-/issues/1558 if I decide to do so. Thanks!

**Comment by licaon-kter** [comment]
One does not just upload an APK to F-Droid.

F-Droid build from source, open-source code only. :)

**Comment by tylerbwong** [comment]
@licaon-kter Ah yes of course, my mistake! 😁

**Comment by tylerbwong** [comment]
I have decided to proceed with adding this app to the F-Droid repository and will be working on getting it ready over the next couple weeks! Thanks again @532910 and @licaon-kter!

**Comment by tylerbwong** [comment]
So sorry to everyone waiting on this. I haven't gotten around to starting the process for F-Droid unfortunately. As a workaround, I have started publishing non-Google Play versions of the app (the base variant) to the [Releases](https://github.com/tylerbwong/stack/releases) page.

**Comment by licaon-kter** [comment]
Why was this closed?

If one can build a fully FOSS app that's nice... you mean this is ready for inclusion?

**Comment by KaKi87** [comment]
How about publishing to a third-party repository like [IzzyOnDroid](https://gitlab.com/IzzyOnDroid/repo#why-another-repository-hasnt-f-droid-its-own) ?
