### ISSUE TITLE
Switching sites requires logging out

### ISSUE THREAD

**Issue by 532910** [tylerbwong/stack#111]
It's too inconvenient to re-login every time on site change.

**Comment by tylerbwong** [comment]
Hey @532910, I definitely agree that switching sites is very inconvenient right now. I would like to move to a solution that is closer to parity with the original Stack Exchange App that shows all of your sites with associated accounts and has no browsing restrictions when it comes to search.

There has already been some discussion around this limitation in #83, so feel free to follow/contribute to that issue for upcoming changes to how this app handles multiple sites. Thanks for the report!
