### ISSUE TITLE
Add non-true-amoled dark mode

### ISSUE THREAD

**Issue by sbeve72** [tylerbwong/stack#114]
true amoled is cool but it makes things hard to read.

Grayish dark mode like in google apps would be appreciated

**Comment by sbeve72** [comment]
Also if you see this issue, can you tell me if its possible to write comments in this app? I know you can write answers but I cant seem to find a way to write comments.

**Comment by tylerbwong** [comment]
> Also if you see this issue, can you tell me if its possible to write comments in this app? I know you can write answers but I cant seem to find a way to write comments.

Hey @sbeve72 thanks for the issue! Currently there is no way to comment on an answer/question as that is being tracked by #109.

**Comment by tylerbwong** [comment]
The latest version of the app ([2.0.0](https://github.com/tylerbwong/stack/releases/tag/2.0.0)) that was just released does not have an amoled dark mode anymore.

Also, commenting was added in that release as well.
