### ISSUE TITLE
Text disappears when screen rotates

### ISSUE THREAD

**Issue by svcop3** [tylerbwong/stack#116]
**Describe the bug**
When posting  a response, rotate the screen after typing text. The text is deleted. 

**To Reproduce**
1.open question
2.click answer
3.type text
4.rotate screen

**Expected behavior**
Text is not deleted

**Screenshots**

**Device Info (please complete the following information):**
 - Device: Redmi 5
 - OS: android 8.1.0
 - Browser:
 - Version:

**Additional context**

**Comment by tylerbwong** [comment]
Fixed by 2404db76f6406dd3d9699e61fb16a2a6fe0176d9
