### ISSUE TITLE
API 2.3 for Stack Exchange

### ISSUE THREAD

**Issue by JourneymanGeek** [tylerbwong/stack#121]
There's a release of a new API version with a few new tools - mostly related to collectives that got released 

Meta post [here ](https://meta.stackexchange.com/questions/366977/api-2-3-release) and [API change log here](https://api.stackexchange.com/docs/change-log) - might be some useful stuff there

**Comment by tylerbwong** [comment]
Thanks for the heads up! Articles would definitely be a nice addition.

**Comment by tylerbwong** [comment]
Closing this out for now as there are no plans to add collectives yet. Patiently awaiting 2.4 with a new Saves API hopefully 🤞
