### ISSUE TITLE
New post button missing

### ISSUE THREAD

**Issue by gryp92k9** [tylerbwong/stack#125]
Describe the bug

To Reproduce

Just launch the app
No new post button in all four tabs
Expected behavior
A button to create new post

Device Info (please complete the following information):

Device: Xiaomi 11
OS: MIUI with Android
Version: 1.0.4
There should be a button to create a new question post right? or just i am too dumb to figure out how to add new post

**Comment by tylerbwong** [comment]
Hey @gryp92k9, unfortunately for the time being there is no way to contribute new posts to any site as this app is mostly a "read-only" app with the exception of posting answers and adding bookmarks. We will hopefully be adding support for adding new posts in the future!

**Comment by tylerbwong** [comment]
Closing as a duplicate of #118
