### ISSUE TITLE
Not showing logged in user after network error

### ISSUE THREAD

**Issue by pisoj** [tylerbwong/stack#127]
I opened the app with the internet disabled, so it showed a `network error`. After I enabled the internet and clicked `retry`, it successfully logged me in and loaded questions, but it **didn't show that I'm logged in, in the top bar**.

**Steps to reproduce the bug:**
1. Make sure that you are logged in
2. Open the app with internet disabled
3. Enable the internet and click `retry` in the snackbar
4. When you click on the account icon in the status bar, the app will prompt you to login, but if you go to settings, you will see that you are already logged in.

I'm using Stack version `1.0.4 (14)`, from Play store.

<video src="https://user-images.githubusercontent.com/87895700/206863825-23d35c77-1af0-4b39-bb42-d1efd5fa629e.mp4">

**Comment by tylerbwong** [comment]
Hey @pisoj, I just released version 2.0 of the app which doesn't have the user profile icon on the main screen anymore, so this shouldn't be an issue. Thanks for the bug report though!
