### ISSUE TITLE
[Feature request] Display duplicate notice & link to duplicated post

### ISSUE THREAD

**Issue by KaKi87** [tylerbwong/stack#128]
**Is your feature request related to a problem? Please describe.**
When opening a post on Stack, there's no way to see that the post is a duplicate nor visit the duplicated post.

**Describe the solution you'd like**
Display a duplicate notice at the top of the post, pretty much the same way as the website does.

**Describe alternatives you've considered**
None

**Additional context**
None

---
Thanks

**Comment by tylerbwong** [comment]
Good suggestion! I added something like it as seen in the screenshot below:

<img src="https://user-images.githubusercontent.com/5953895/218941462-e8ef2b42-4f8a-46c3-8e25-8eb582412d93.jpg" width="250" />
