### ISSUE TITLE
"TextFieldValue(text=…" in questions asked from the app

### ISSUE THREAD

**Issue by mserranomartin** [tylerbwong/stack#133]
![Screenshot_20230315-224710](https://user-images.githubusercontent.com/63246434/225451844-0c674551-eb3e-483a-b7e7-095d13560469.jpg)

**Comment by tylerbwong** [comment]
Will fix this ASAP and push out a fix. Thanks for using the app and filing the bug report!

**Comment by tylerbwong** [comment]
Fixed in deae63b259bafe1dd91c16c6361b977887a61354
