### ISSUE TITLE
Crashes on opening some links

### ISSUE THREAD

**Issue by cdubthecoolcat** [tylerbwong/stack#22]
Not sure why anyone would go to it instead of just opening the app, but the app crashes nonetheless.

Reproduce:
1.  Open web browser
2.  Google search "stackoverflow."
3.  Select one of the sublinks under the official website, ie. "Questions"
4.  ??
5.  Crashes

It happens with other sublinks as well.

**Comment by tylerbwong** [comment]
Can reproduce! Will work on a fix 👍

**Comment by tylerbwong** [comment]
Fixed in 61927eb63f962f8589ab7caac28c4ca3fde8e5fe
