### ISSUE TITLE
Handle Offline State Better

### ISSUE THREAD

**Issue by tylerbwong** [tylerbwong/stack#77]
Currently only a `Snackbar` is being shown when there is no internet. We can improve this experience by:

1. Showing an empty view for whichever screen the user is on and
2. Determine the cause of request failure and if the lack of network is detected, launch a settings `Intent` or use [settings panels (Android 10+)](https://developer.android.com/about/versions/10/features#settings-panels) to allow the user to turn their internet back on from within the app.

**Comment by pisoj** [comment]
I will look at this. 👀
