### ISSUE TITLE
Add In-App Review Support

### ISSUE THREAD

**Issue by tylerbwong** [tylerbwong/stack#78]
https://developer.android.com/guide/playcore/in-app-review

**Comment by abhinav78910** [comment]
Can i work on this @tylerbwong

**Comment by tylerbwong** [comment]
Hey @abhinav78910 of course! Just so you know the project structure is changing a little bit in #112 (in case that happens to merge first).

**Comment by abhinav78910** [comment]
Hi @tylerbwong , I am not able to sync the project. Can you help me with this. I have enclosed the error - 
This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 4.3 or newer.
I have checked the latest android studio version but it's still 4.1.1 so do i need to install canary version to work on the project?

**Comment by tylerbwong** [comment]
Hey @abhinav78910, yes the latest [Canary version of Android Studio](https://developer.android.com/studio/preview) is required to build this project since it uses Jetpack Compose.
