### ISSUE TITLE
Allow Bookmark Sync Frequency Configuration

### ISSUE THREAD

**Issue by tylerbwong** [tylerbwong/stack#81]
Currently the sync interval is every 8 hours for offline bookmark syncing. It would be nice if this were configurable from settings.

**Comment by LandonPatmore** [comment]
It is setup in Dagger, so it is a compile time dependency.  Looks like it will need to be broken out it out into a runtime component.

**Comment by tylerbwong** [comment]
@LandonPatmore That's a good point. Currently all work requests are created and managed by Hilt's `SingletonComponent` object graph so we will need to break it out into its own component that we can manage/recreate when needed.

**Comment by tylerbwong** [comment]
After doing a little research it seems like we'll be able to cancel existing unique work enqueued by `WorkManager`. So this feature will just be a matter of saving the sync interval to disk, canceling the old `WorkRequest` and then enqueuing a new one with the new sync interval.

However, bookmark background sync is currently disabled due to a bug 😞.

**Comment by tylerbwong** [comment]
Closing due to #126 for the time being.
