### ISSUE TITLE
"Network error"

### ISSUE THREAD

**Issue by XPMai** [tylerbwong/stack#93]
**Describe the bug**
When I open Stack app, I cannot browse anything because it says "Network error"

**To Reproduce**
1. Open Stack app
2. Press on a post
3. "Network error" ![Screenshot_20201021-145806_Stack](https://user-images.githubusercontent.com/6212927/96684827-ce38d380-13ae-11eb-85fc-d6cfe86a978f.jpg)
4.

**Expected behavior**
Load the content

**Screenshots**

**Device Info (please complete the following information):**
 - Device: Note 8
 - OS: Android 8.0
 - Browser: N/A
 - Version: 1.0.2 (12)

**Additional context**
This issue didn't exist when I first installed it

**Comment by tylerbwong** [comment]
Hey @XPMai thanks for reporting this. If possible do you think you can provide me with more info?

1. Are you logged in? and if so
2. Do you have any saved bookmarks or answer drafts?
3. Do you happen to have a link to the question you were trying to view?

**Comment by tylerbwong** [comment]
Another thing, does clearing app data fix the issue at all?

**Comment by SpeedyLom** [comment]
I'm also getting this but from the search screen.

When the search screen loads if I click on a popular tag (e.g. `php`) it'll often display "Network Error".

![Screenshot_20201104-162845.jpg](https://user-images.githubusercontent.com/10461862/98166162-e7796e00-1ede-11eb-90e0-449a289a526f.jpg)

**Comment by tylerbwong** [comment]
Hey @SpeedyLom, thanks for the detailed report and screenshot.

Just to make sure, do other parts of the app work? (question details, bookmarks, etc.) I remember you mentioned profiles also show "Network error" for you intermittently as well.

Also, does the issue persist if you log out?

A few things that I think could be related to this issue are:

1. Somehow a bad auth token is getting appended.
2. The StackExchange API itself is returning an internal error that we can't control. (I've been seeing a few 503s returned from the API on my end)

**Comment by SpeedyLom** [comment]
The list of questions always loads as far as I have seen.

The next time it happens I'll try the other bits and come back to you.

**Comment by SpeedyLom** [comment]
I got some screenshots of the other screens when it happens. Once I logged out and logged back in again I was able to use the app as expected.

I'll let you know if it happens anymore now that I have refreshed my login.

```
Question details
```
![question](https://user-images.githubusercontent.com/10461862/98216463-04df2400-1f41-11eb-9504-7df88f368768.jpg)
```
Search
```
![search](https://user-images.githubusercontent.com/10461862/98216464-0577ba80-1f41-11eb-84e8-4cd8e47c3212.jpg)

```
Profile
```
![profile](https://user-images.githubusercontent.com/10461862/98216466-06105100-1f41-11eb-8142-263bb81183f0.jpg)

**Comment by tylerbwong** [comment]
@SpeedyLom Thanks so much for the screenshots and refreshing login. I suspect somehow the existing access token got invalidated somehow and was causing errors in the request. I'll continue to look into how this could've happened. Again, really appreciate the reports!

**Comment by SpeedyLom** [comment]
I am still getting the issue since I refreshing the login last time 😔

**Comment by tylerbwong** [comment]
@SpeedyLom I'm so sorry this keeps happening to you :disappointed:.

If you are willing, I'd really like to connect further so that we can work more closely on this issue. Feel free to shoot me an e-mail at tbwong3@gmail.com if you'd like, since debugging authentication issues can be sensitive. Unfortunately I'm not able to see much info on my side since error logs are a bit vague so the next best thing would be to install a debug build so you can inspect HTTP logs.

**Comment by tylerbwong** [comment]
Ok good news! I encountered this error during development on one of my devices and it does not seem to be related to authentication at all. There's a bug somewhere that is causing a ton of requests to be made to the Stack Exchange API at once, and the server is responding with a 503 error. Will be looking into fixing this bug soon :+1:

**Comment by tylerbwong** [comment]
@XPMai @SpeedyLom Thank you both once again for helping track down this issue! I just uploaded a new release to the Play Store and it is under review. Hopefully we'll see this fixed once it goes live.
